name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  - master
pr:
  - master
jobs:
- job: windows
  displayName: Windows Build
  pool:
    vmImage: windows-latest
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ..
  -task: CMake@1
    inputs:
      cmakeArgs: --build . --config Release